const historyContkrtKr = [
  {
    index: 0,
    year: '1997',
    month: '04',
    en: 'LG Chemical',
    kr: 'LG화학 오키나와 총대리점으로 사업을 시작',
    group: -1,
  },
  {
    index: 1,
    year: '1997',
    month: '09',
    en: 'LG Chemical',
    kr: '오키나와TNT 로 사명을 변경',
    group: -1,
  },
  {
    index: 2,
    year: '1998',
    month: '05',
    en: 'LG Chemical',
    kr: 'LG화학 호주 및 뉴질랜드 지역 판매권 획득',
    group: -1,
  },
  {
    index: 3,
    year: '1999',
    month: '05',
    en: 'LG Chemical',
    kr: '현 비즈니스 채널의 모태가 되는 오키나와TNT 한국지사 설립',
    group: -1,
  },
  {
    index: 4,
    year: '2000',
    month: '06',
    en: 'LG Chemical',
    kr: 'LG건설 오키나와 판매권 획득, CJ 오키나와 및 북해도 펫푸드 판매 개시',
    group: -1,
  },
  {
    index: 5,
    year: '2001',
    month: '03',
    en: 'LG Chemical',
    kr: '동원산업, 롯데칠성, 한샘시스템키친 오키나와 대리점권 획득',
    group: -1,
  },
  {
    index: 6,
    year: '2002',
    month: '02',
    en: 'LG Chemical',
    kr: '대만 유니프레지던트, 신호스틸, KCC건축자재 오키나와 대리점 획득',
    group: -1,
  },
  {
    index: 7,
    year: '2003',
    month: '08',
    en: 'LG Chemical',
    kr: '본사 겸 창고 사옥 완성',
    group: -1,
  },
  {
    index: 8,
    year: '2003',
    month: '09',
    en: 'LG Chemical',
    kr: '사명을 오키나와TNT 에서 월드TNT로 변경',
    group: -1,
  },
  {
    index: 9,
    year: '2003',
    month: '10',
    en: 'LG Chemical',
    kr: 'JINRO 오키나와 대리점 획득',
    group: -1,
  },
  {
    index: 10,
    year: '2004',
    month: '02',
    en: 'LG Chemical',
    kr: '월드티앤티 호주지사 설립',
    group: -1,
  },
  {
    index: 11,
    year: '2004',
    month: '03',
    en: 'LG Chemical',
    kr: '보세창고 등록 완료',
    group: -1,
  },
  {
    index: 12,
    year: '2004',
    month: '11',
    en: 'LG Chemical',
    kr: '아사히카세이 대리점 권한 획득',
    group: -1,
  },
  {
    index: 13,
    year: '2008',
    month: '04',
    en: 'LG Chemical',
    kr: 'LG생활건강 전일본 대리권 획득',
    group: -1,
  },
  {
    index: 14,
    year: '2008',
    month: '09',
    en: 'LG Chemical',
    kr:
      '한국 농수산물유통공사 선정 일본 유망수출 기업 인증 / 오뚜기, 진로, 상일 등과 수출계약 체결',
    group: -1,
  },
  {
    index: 15,
    year: '2009',
    month: '04',
    en: 'LG Chemical',
    kr: '한국법인 주식회사 비즈니스채널 설립',
    group: -1,
  },
  {
    index: 16,
    year: '2010',
    month: '',
    en: 'LG Chemical',
    kr:
      '주식회사 히메프라, 로케트세켄 주식회사, 코스모스 약품, 쯔루하드럭 등 오키나와 중심의 영업활동을 본격적으로 일본 본토로 확대 / LG생활건강 전일본 대리점 권한을 마루베니상사에 판매',
    group: -1,
  },
  {
    index: 17,
    year: '2011',
    month: '03',
    en: 'LG Chemical',
    kr: '중소기업청 선정 유망수출업체 지정 도쿄 토라노몽 사무소 설립',
    group: -1,
  },
  {
    index: 18,
    year: '2012',
    month: '03',
    en: 'LG Chemical',
    kr:
      '미국 Super Value 등 미주지역 밴더와 US 및 멕시코 P&G 제품 한국시장 공급. 본격적으로 한국 시장 진출 전략 수립. 주식회사 명경통상 설립',
    group: -1,
  },
  {
    index: 19,
    year: '2016',
    month: '',
    en: 'LG Chemical',
    kr:
      '쯔루하 그룹에 신규 제3맥주 ‘무기쯔야’ 판매 개시 / 자사의 가구 및 화장지 브랜드 Tree Wear 를 런칭 / APP 및 GUTK와 협력하여 PASEO 화장지 브랜드 런칭 / JINRO 재팬과 업무제휴, JINRO재팬 일본 전국 영업망을 활용한 잡화류 영업을 개시 / 주식회사 미래생활 화장지 제품에 대한 전일본 대리점 권한 획득',
    group: -1,
  },
  {
    index: 20,
    year: '2017',
    month: '',
    en: 'LG Chemical',
    kr:
      '국내 전자상거래 통신업 등록 및 온라인 사업 확대 / 이마트몰, 롯데닷컴, 11번가 등',
    group: -1,
  },
];

export default historyContkrtKr;
